---
title: "My_sample_variance"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{My_sample_variance}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(Variance)
```


## Create some data

First we will check that sample mean gives correct value by calculating the sample mean for the numbers 1 to 10. 

```{r}
x  <- 1:10
```

## Using the `my_mean()` function

The `my_mean()` function will take a numeric vector

$$
x_1, x_2, \ldots, x_n
$$

and return the sample variance:

$$
\bar{x} = \frac1{n} \sum^n_{i = 1}x_i\\

S_{n}^{2} = \frac1{n-1} \sum^n_{i = 1}x_i^2
$$



```{r}
my_variance(x)
```

We can check this is correct with 

$$

\bar x = \frac{1}{10}(1 + 2 + \ldots + 10) = \frac{1}{10}\times \frac{11\times10}{2} = 5.5.\\

 S_{10}^{2}= \frac{1}{10-1}((1-5.5)^2+ (2-5.5)^2 + \ldots + (10-5.5)^2) = \frac{1}{9}\times \frac{10\times11\times21}{6} = 9.17.
$$
